name: stare
dependencies:
  - python=3.10
  - pytorch
  - pip
  - pip:
    - torchvision
    - numpy
    - diffusers
    - transformers
    - accelerate
    - opencv-python
    - tqdm
    - scenedetect
    - matplotlib
    - jupyter